interface IFormInput {
  uid?: string;
  display_name?: string;
  display_image?: string;
  CardiovascularSystem?: string[];
  EarEyesThroatAndNoseSystem?: string[];
  ImmuneSystem?: string[];
  MusculoskeletalSystem?: string[];
  NervousSystem?: string[];
  PsychiatricSystem?: string[];
  RespiratorySystem?: string[];
  SkinSystem?: string[];
  StomachAndIntestinalSystem?: string[];
  Symptom?: string[];
}
interface IFormInputOld {
  uid?: string;
  display_name?: string;
  display_image?: string;
  prefix_name?: string;
  prefix_nameEtc?: string | undefined;
  first_name?: string;
  last_name?: string;
  identity_card?: string;
  gender?: string;
  age?: string;
  weight?: string;
  nationality?: string;
  nationalityEtc?: string | undefined;
  married_status?: string;
  married_statusEtc?: string | undefined;
  current_address?: string;
  district?: string;
  sub_district?: string;
  province?: string;
  post_code?: string;
  phone_number?: string;
  items_medicine?: string[];
  items_medicineEtc?: string | undefined;
  covid19_result?: string;
  covid19_resultEtc?: string | undefined;
  received_favipiravir?: string;
  received_favipiravir_detail?: string;
  pregnant?: string;
  pregnantEtc?: string | undefined;
  hepatitis?: string;
  hepatitisEtc?: string | undefined;
  symptoms_tiredness?: string;
  symptoms_tirednessEtc?: string | undefined;
  diabetes?: string;
  diabetesEtc?: string | undefined;
  peptic_ulcer_disease?: string;
  peptic_ulcer_diseaseEtc?: string | undefined;
  symptoms?: string[];
  symptomsEtc?: string | undefined;
  days_symptoms?: string;
  congenital_diseases?: string[];
  congenital_diseasesEtc?: string | undefined;
  history_drug_allergy?: string;
  color?: string;
  reserve_bed?: string;
  date_diagnosis?: string;
  date_result_covid?: string;
}

export default IFormInput;
